export const seededSites = [
  {
    slug: "pierlimo",
    name: "Pierlimo",
    domain: "pierlimo.com",
    themeKey: "pierlimo",
  },
  {
    slug: "seatac_co",
    name: "seatac.co",
    domain: "seatac.co",
    themeKey: "seatac_co",
  },
] as const;

export const seededSiteData = {
  pierlimo: {
    chauffeurs: [
      {
        name: "Ameer Nuri",
        phone: "(206) 555-0112",
        color: "emerald",
        displayOrder: 1,
      },
      {
        name: "Maya Chen",
        phone: "(206) 555-0118",
        color: "sky",
        displayOrder: 2,
      },
      {
        name: "Jordan Alvarez",
        phone: "(206) 555-0147",
        color: "amber",
        displayOrder: 3,
      },
    ],
    vehicles: [
      {
        slug: "executive-sedan",
        name: "Executive Sedan",
        summary:
          "Discrete black-car service for Sea-Tac transfers, boardroom arrivals, and downtown hotel pickups.",
        passengersMin: 1,
        passengersMax: 3,
        bagsMin: 0,
        bagsMax: 3,
        quantity: 3,
        basePrice: "95.00",
        perMileRate: "3.25",
        hourlyRate: "95.00",
        image: "/vehicles/airport-sedan.png",
        displayOrder: 1,
      },
      {
        slug: "luxury-suv",
        name: "Luxury SUV",
        summary:
          "Executive comfort with extra luggage room for Bellevue runs, investor dinners, and family airport departures.",
        passengersMin: 1,
        passengersMax: 6,
        bagsMin: 0,
        bagsMax: 6,
        quantity: 2,
        basePrice: "135.00",
        perMileRate: "4.15",
        hourlyRate: "125.00",
        image: "/vehicles/airport-suv.png",
        displayOrder: 2,
      },
      {
        slug: "sprinter-van",
        name: "Sprinter Van",
        summary:
          "Group movement for wedding parties, conference teams, and multi-stop private transportation.",
        passengersMin: 4,
        passengersMax: 12,
        bagsMin: 2,
        bagsMax: 12,
        quantity: 1,
        basePrice: "245.00",
        perMileRate: "6.50",
        hourlyRate: "185.00",
        image: "/vehicles/sprinter-van.png",
        displayOrder: 3,
        siteAssignments: ["pierlimo", "seatac_co"],
      },
    ],
    routes: [
      {
        slug: "seatac-downtown-seattle",
        name: "Sea-Tac Airport to Downtown Seattle",
        mode: "airport",
        origin: "Sea-Tac Airport",
        destination: "Downtown Seattle",
        basePrice: "118.00",
        mileage: "15.00",
        durationMinutes: 28,
      },
      {
        slug: "seatac-bellevue",
        name: "Sea-Tac Airport to Bellevue",
        mode: "airport",
        origin: "Sea-Tac Airport",
        destination: "Bellevue",
        basePrice: "132.00",
        mileage: "18.00",
        durationMinutes: 32,
      },
      {
        slug: "seatac-redmond",
        name: "Sea-Tac Airport to Redmond",
        mode: "airport",
        origin: "Sea-Tac Airport",
        destination: "Redmond",
        basePrice: "146.00",
        mileage: "24.00",
        durationMinutes: 40,
      },
      {
        slug: "downtown-bellevue-corporate",
        name: "Downtown Seattle to Bellevue Corporate Corridor",
        mode: "corporate",
        origin: "Downtown Seattle",
        destination: "Bellevue",
        basePrice: "124.00",
        mileage: "12.00",
        durationMinutes: 26,
      },
      {
        slug: "bellevue-redmond-corporate",
        name: "Bellevue to Redmond Tech Campus",
        mode: "corporate",
        origin: "Bellevue",
        destination: "Redmond",
        basePrice: "112.00",
        mileage: "10.00",
        durationMinutes: 24,
      },
      {
        slug: "hourly-seattle-minimum",
        name: "Seattle Hourly Charter",
        mode: "hourly",
        origin: "Flexible pickup",
        destination: "As directed",
        basePrice: "0.00",
        mileage: "0.00",
        durationMinutes: 0,
      },
    ],
    settings: {
      companyName: "Pierlimo",
      dispatchPhone: "(206) 208-0996",
      dispatchEmail: "reservations@pierlimo.com",
      dispatchRules: {
        pickupBufferMinutes: 60,
        dropoffBufferMinutes: 60,
        minimumTransferMinutes: 15,
        fallbackTransferMinutes: 30,
        defaultRouteDurationMinutes: 90,
      },
      bookingConstraints: {
        customTripDefaultPricing: "distance",
        enableDistancePricing: true,
        enableFlatPricing: true,
        enableHourlyPricing: true,
        chargeBagsOnDistance: false,
        chargeBagsOnEvent: false,
        chargeBagsOnFlat: false,
        chargeBagsOnHourly: false,
        chargeMileageOnDistance: true,
        chargeMileageOnEvent: false,
        chargeMileageOnFlat: false,
        chargeMileageOnHourly: false,
        chargePassengersOnDistance: false,
        chargePassengersOnEvent: false,
        chargePassengersOnFlat: false,
        chargePassengersOnHourly: false,
        perMileFee: 0,
        perBagFee: 0,
        perPassengerFee: 0,
        hourlyMinimumHours: 3,
        hourlyServiceFee: 0,
        minimumLeadMinutes: 120,
        operatingHoursStart: "04:00",
        operatingHoursEnd: "23:00",
        maxAdvanceDays: 180,
        presetRouteDefaultPricing: "flat",
        timeZone: "America/Los_Angeles",
      },
      coverage: [
        "Sea-Tac Airport",
        "Downtown Seattle",
        "Bellevue",
        "Redmond",
        "Kirkland",
        "Mercer Island",
        "South Lake Union",
        "Capitol Hill",
        "Waterfront hotels",
      ],
    },
  },
  seatac_co: {
    chauffeurs: [
      {
        name: "Devin Brooks",
        phone: "(206) 555-0191",
        color: "violet",
        displayOrder: 1,
      },
      {
        name: "Sofia Patel",
        phone: "(206) 555-0184",
        color: "rose",
        displayOrder: 2,
      },
      {
        name: "Elias Grant",
        phone: "(206) 555-0166",
        color: "slate",
        displayOrder: 3,
      },
    ],
    vehicles: [
      {
        slug: "airport-sedan",
        name: "Airport Sedan",
        summary:
          "Focused Sea-Tac black-car service for direct terminal pickups, departures, and clean downtown drop-offs.",
        passengersMin: 1,
        passengersMax: 3,
        bagsMin: 0,
        bagsMax: 3,
        quantity: 3,
        basePrice: "89.00",
        perMileRate: "3.10",
        hourlyRate: "90.00",
        image: "/vehicles/airport-sedan.png",
        displayOrder: 1,
      },
      {
        slug: "airport-suv",
        name: "Airport SUV",
        summary:
          "Extra luggage room for families, tech travelers, and Bellevue airport transfers.",
        passengersMin: 1,
        passengersMax: 6,
        bagsMin: 0,
        bagsMax: 6,
        quantity: 2,
        basePrice: "129.00",
        perMileRate: "4.05",
        hourlyRate: "122.00",
        image: "/vehicles/airport-suv.png",
        displayOrder: 2,
      },
    ],
    routes: [
      {
        slug: "seatac-downtown-core",
        name: "Sea-Tac to Downtown Seattle",
        mode: "airport",
        origin: "Seattle-Tacoma International Airport, 17801 International Blvd, SeaTac, WA 98158, USA",
        destination: "Downtown Seattle, Seattle, WA, USA",
        basePrice: "109.00",
        mileage: "15.00",
        durationMinutes: 27,
      },
      {
        slug: "seatac-bellevue-core",
        name: "Sea-Tac to Bellevue",
        mode: "airport",
        origin: "Seattle-Tacoma International Airport, 17801 International Blvd, SeaTac, WA 98158, USA",
        destination: "Downtown Bellevue, Bellevue, WA, USA",
        basePrice: "124.00",
        mileage: "18.00",
        durationMinutes: 31,
      },
      {
        slug: "seatac-kirkland-core",
        name: "Sea-Tac to Kirkland",
        mode: "airport",
        origin: "Seattle-Tacoma International Airport, 17801 International Blvd, SeaTac, WA 98158, USA",
        destination: "Kirkland, WA, USA",
        basePrice: "138.00",
        mileage: "23.00",
        durationMinutes: 38,
      },
      {
        slug: "downtown-seatac-core",
        name: "Downtown Seattle to Sea-Tac",
        mode: "airport",
        origin: "Downtown Seattle, Seattle, WA, USA",
        destination: "Seattle-Tacoma International Airport, 17801 International Blvd, SeaTac, WA 98158, USA",
        basePrice: "109.00",
        mileage: "15.00",
        durationMinutes: 30,
      },
      {
        slug: "bellevue-seatac-core",
        name: "Bellevue to Sea-Tac",
        mode: "airport",
        origin: "Downtown Bellevue, Bellevue, WA, USA",
        destination: "Seattle-Tacoma International Airport, 17801 International Blvd, SeaTac, WA 98158, USA",
        basePrice: "124.00",
        mileage: "18.00",
        durationMinutes: 34,
      },
      {
        slug: "kirkland-seatac-core",
        name: "Kirkland to Sea-Tac",
        mode: "airport",
        origin: "Kirkland, WA, USA",
        destination: "Seattle-Tacoma International Airport, 17801 International Blvd, SeaTac, WA 98158, USA",
        basePrice: "138.00",
        mileage: "23.00",
        durationMinutes: 42,
      },
      {
        slug: "seatac-pier-66",
        name: "Sea-Tac to Pier 66",
        mode: "airport",
        origin: "Seattle-Tacoma International Airport, 17801 International Blvd, SeaTac, WA 98158, USA",
        destination: "Bell Street Cruise Terminal at Pier 66, 2225 Alaskan Way, Seattle, WA 98121, USA",
        basePrice: "136.00",
        mileage: "17.00",
        durationMinutes: 34,
      },
      {
        slug: "seatac-pier-91",
        name: "Sea-Tac to Pier 91",
        mode: "airport",
        origin: "Seattle-Tacoma International Airport, 17801 International Blvd, SeaTac, WA 98158, USA",
        destination: "Smith Cove Cruise Terminal at Pier 91, 2001 W Garfield St, Seattle, WA 98119, USA",
        basePrice: "148.00",
        mileage: "19.00",
        durationMinutes: 38,
      },
      {
        slug: "seatac-airport-hotels-core",
        name: "Sea-Tac to Airport Hotels",
        mode: "airport",
        origin: "Seattle-Tacoma International Airport, 17801 International Blvd, SeaTac, WA 98158, USA",
        destination: "SeaTac Airport Marriott, 3201 S 176th St, Seattle, WA 98188, USA",
        basePrice: "96.00",
        mileage: "4.00",
        durationMinutes: 12,
      },
      {
        slug: "pier-66-seatac",
        name: "Pier 66 to Sea-Tac",
        mode: "airport",
        origin: "Bell Street Cruise Terminal at Pier 66, 2225 Alaskan Way, Seattle, WA 98121, USA",
        destination: "Seattle-Tacoma International Airport, 17801 International Blvd, SeaTac, WA 98158, USA",
        basePrice: "136.00",
        mileage: "17.00",
        durationMinutes: 37,
      },
      {
        slug: "pier-91-seatac",
        name: "Pier 91 to Sea-Tac",
        mode: "airport",
        origin: "Smith Cove Cruise Terminal at Pier 91, 2001 W Garfield St, Seattle, WA 98119, USA",
        destination: "Seattle-Tacoma International Airport, 17801 International Blvd, SeaTac, WA 98158, USA",
        basePrice: "148.00",
        mileage: "19.00",
        durationMinutes: 41,
      },
      {
        slug: "downtown-bellevue-business",
        name: "Downtown Seattle to Bellevue Business Corridor",
        mode: "corporate",
        origin: "Downtown Seattle, Seattle, WA, USA",
        destination: "Downtown Bellevue, Bellevue, WA, USA",
        basePrice: "118.00",
        mileage: "12.00",
        durationMinutes: 25,
      },
      {
        slug: "seatac-hourly-charter",
        name: "SeaTacDrive Hourly Charter",
        mode: "hourly",
        origin: "Flexible pickup",
        destination: "As directed",
        basePrice: "0.00",
        mileage: "0.00",
        durationMinutes: 0,
      },
    ],
    hotels: [
      {
        slug: "coast-gateway-hotel",
        name: "Coast Gateway Hotel",
        address: "18415 International Blvd, SeaTac, WA 98188, USA",
        neighborhood: "Sea-Tac hotel district",
        area: "seatac-hotels",
        summary:
          "One of the closest hotel options to the terminal for late arrivals, overnight layovers, and early departures.",
        airportRouteSlug: "seatac-airport-hotels-core",
        distanceMiles: "1.20",
        durationMinutes: 5,
        priority: 1,
      },
      {
        slug: "cedarbrook-lodge",
        name: "Cedarbrook Lodge",
        address: "18525 36th Ave S, SeaTac, WA 98188, USA",
        neighborhood: "Sea-Tac hotel district",
        area: "seatac-hotels",
        summary:
          "A quieter airport-area stay for travelers who want a calmer hotel environment without losing easy terminal access.",
        airportRouteSlug: "seatac-airport-hotels-core",
        distanceMiles: "3.40",
        durationMinutes: 9,
        priority: 2,
      },
      {
        slug: "doubletree-seatac",
        name: "DoubleTree by Hilton Seattle Airport",
        address: "18740 International Blvd, Seattle, WA 98188, USA",
        neighborhood: "Sea-Tac hotel district",
        area: "seatac-hotels",
        summary:
          "A large airport hotel base that works well for conference guests, overnight stays, and family arrivals with luggage.",
        airportRouteSlug: "seatac-airport-hotels-core",
        distanceMiles: "1.90",
        durationMinutes: 6,
        priority: 3,
      },
      {
        slug: "hilton-seattle-airport-conference-center",
        name: "Hilton Seattle Airport & Conference Center",
        address: "17620 International Blvd, Seattle, WA 98188, USA",
        neighborhood: "Sea-Tac hotel district",
        area: "seatac-hotels",
        summary:
          "A practical airport hotel for overnight stays, conferences, and travelers who want an easy return to the terminal the next day.",
        airportRouteSlug: "seatac-airport-hotels-core",
        distanceMiles: "1.40",
        durationMinutes: 5,
        priority: 4,
      },
      {
        slug: "seattle-airport-marriott",
        name: "Seattle Airport Marriott",
        address: "3201 S 176th St, Seattle, WA 98188, USA",
        neighborhood: "Sea-Tac hotel district",
        area: "seatac-hotels",
        summary:
          "An airport-area stay that works well for one-night stopovers, business guests, and travelers who want a short ride after landing.",
        airportRouteSlug: "seatac-airport-hotels-core",
        distanceMiles: "1.80",
        durationMinutes: 6,
        priority: 5,
      },
      {
        slug: "crowne-plaza-seattle-airport",
        name: "Crowne Plaza Seattle Airport",
        address: "17338 International Blvd, Seattle, WA 98188, USA",
        neighborhood: "Sea-Tac hotel district",
        area: "seatac-hotels",
        summary:
          "A straightforward airport hotel option for overnight stays, early flights, and short transfers from Sea-Tac.",
        airportRouteSlug: "seatac-airport-hotels-core",
        distanceMiles: "1.10",
        durationMinutes: 5,
        priority: 6,
      },
      {
        slug: "radisson-hotel-seattle-airport",
        name: "Radisson Hotel Seattle Airport",
        address: "18118 International Blvd, Seattle, WA 98188, USA",
        neighborhood: "Sea-Tac hotel district",
        area: "seatac-hotels",
        summary:
          "A practical airport stay for overnight stops, early departures, and travelers who want a straightforward ride after landing.",
        airportRouteSlug: "seatac-airport-hotels-core",
        distanceMiles: "1.30",
        durationMinutes: 5,
        priority: 21,
      },
      {
        slug: "red-lion-hotel-seattle-airport",
        name: "Red Lion Hotel Seattle Airport",
        address: "18220 International Blvd, Seattle, WA 98188, USA",
        neighborhood: "Sea-Tac hotel district",
        area: "seatac-hotels",
        summary:
          "A familiar airport hotel choice for late arrivals, short overnight stays, and next-morning flights.",
        airportRouteSlug: "seatac-airport-hotels-core",
        distanceMiles: "1.40",
        durationMinutes: 5,
        priority: 22,
      },
      {
        slug: "hampton-inn-suites-seatac-28th-ave",
        name: "Hampton Inn & Suites Seattle-Airport/28th Ave",
        address: "18850 28th Ave S, SeaTac, WA 98188, USA",
        neighborhood: "Sea-Tac hotel district",
        area: "seatac-hotels",
        summary:
          "An airport district stay that works well for families, quick overnight stops, and easy return trips to the terminal.",
        airportRouteSlug: "seatac-airport-hotels-core",
        distanceMiles: "2.00",
        durationMinutes: 7,
        priority: 23,
      },
      {
        slug: "hilton-garden-inn-seattle-airport",
        name: "Hilton Garden Inn Seattle Airport",
        address: "3056 S 188th St, SeaTac, WA 98188, USA",
        neighborhood: "Sea-Tac hotel district",
        area: "seatac-hotels",
        summary:
          "A useful airport-area stay for short layovers, overnight work trips, and travelers who want a shorter ride from Sea-Tac.",
        airportRouteSlug: "seatac-airport-hotels-core",
        distanceMiles: "2.20",
        durationMinutes: 7,
        priority: 24,
      },
      {
        slug: "aloft-seattle-seatac-airport",
        name: "Aloft Seattle Sea-Tac Airport",
        address: "19030 28th Ave S, SeaTac, WA 98188, USA",
        neighborhood: "Sea-Tac hotel district",
        area: "seatac-hotels",
        summary:
          "A modern airport hotel option for one-night stays, later arrivals, and travelers who want an easy ride to and from the terminal.",
        airportRouteSlug: "seatac-airport-hotels-core",
        distanceMiles: "2.10",
        durationMinutes: 7,
        priority: 25,
      },
      {
        slug: "residence-inn-seatac-airport",
        name: "Residence Inn Seattle Sea-Tac Airport",
        address: "19608 International Blvd, SeaTac, WA 98188, USA",
        neighborhood: "Sea-Tac hotel district",
        area: "seatac-hotels",
        summary:
          "A strong airport choice for longer stays, family luggage, and travelers who want extra room without moving far from Sea-Tac.",
        airportRouteSlug: "seatac-airport-hotels-core",
        distanceMiles: "2.70",
        durationMinutes: 8,
        priority: 26,
      },
      {
        slug: "fairmont-olympic-hotel",
        name: "Fairmont Olympic Hotel",
        address: "411 University St, Seattle, WA 98101, USA",
        neighborhood: "Downtown Seattle",
        area: "downtown-seattle",
        summary:
          "A classic downtown stay for travelers wanting central Seattle access, polished service, and easy connections to meetings or waterfront plans.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.10",
        durationMinutes: 29,
        priority: 7,
      },
      {
        slug: "grand-hyatt-seattle",
        name: "Grand Hyatt Seattle",
        address: "721 Pine St, Seattle, WA 98101, USA",
        neighborhood: "Downtown Seattle",
        area: "downtown-seattle",
        summary:
          "A strong downtown base for convention guests, shopping stays, and travelers who want to stay near central Seattle.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.00",
        durationMinutes: 28,
        priority: 8,
      },
      {
        slug: "westin-seattle",
        name: "The Westin Seattle",
        address: "1900 5th Ave, Seattle, WA 98101, USA",
        neighborhood: "Downtown Seattle",
        area: "downtown-seattle",
        summary:
          "A well-known downtown hotel for central Seattle access, city views, and straightforward Sea-Tac transfers.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.60",
        durationMinutes: 30,
        priority: 9,
      },
      {
        slug: "lotte-hotel-seattle",
        name: "Lotte Hotel Seattle",
        address: "809 5th Ave, Seattle, WA 98104, USA",
        neighborhood: "Downtown Seattle",
        area: "downtown-seattle",
        summary:
          "A polished downtown stay for travelers who want a premium arrival, central access, and a direct airport route into the city core.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.20",
        durationMinutes: 29,
        priority: 10,
      },
      {
        slug: "hotel-1000-seattle",
        name: "Hotel 1000",
        address: "1000 1st Ave, Seattle, WA 98104, USA",
        neighborhood: "Downtown Seattle",
        area: "downtown-seattle",
        summary:
          "A downtown Seattle hotel that works well for business stays, premium city trips, and travelers who want a direct airport pickup into the urban core.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.00",
        durationMinutes: 28,
        priority: 11,
      },
      {
        slug: "hyatt-at-olive-8",
        name: "Hyatt At Olive 8",
        address: "1635 8th Ave, Seattle, WA 98101, USA",
        neighborhood: "Downtown Seattle",
        area: "downtown-seattle",
        summary:
          "A central downtown stay for city weekends, convention plans, and airport arrivals headed straight into the core.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.10",
        durationMinutes: 29,
        priority: 27,
      },
      {
        slug: "sheraton-grand-seattle",
        name: "Sheraton Grand Seattle",
        address: "1400 6th Ave, Seattle, WA 98101, USA",
        neighborhood: "Downtown Seattle",
        area: "downtown-seattle",
        summary:
          "A large downtown hotel for convention traffic, business stays, and direct airport arrivals into central Seattle.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.10",
        durationMinutes: 29,
        priority: 28,
      },
      {
        slug: "motif-seattle",
        name: "Motif Seattle",
        address: "1415 5th Ave, Seattle, WA 98101, USA",
        neighborhood: "Downtown Seattle",
        area: "downtown-seattle",
        summary:
          "A downtown Seattle stay close to retail, theaters, and central hotel drop-offs from Sea-Tac.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.00",
        durationMinutes: 28,
        priority: 29,
      },
      {
        slug: "renaissance-seattle-hotel",
        name: "Renaissance Seattle Hotel",
        address: "515 Madison St, Seattle, WA 98104, USA",
        neighborhood: "Downtown Seattle",
        area: "downtown-seattle",
        summary:
          "A downtown business stay with easy access to central Seattle meetings and a direct airport ride into the city.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.30",
        durationMinutes: 29,
        priority: 30,
      },
      {
        slug: "kimpton-hotel-monaco-seattle",
        name: "Kimpton Hotel Monaco Seattle",
        address: "1101 4th Ave, Seattle, WA 98101, USA",
        neighborhood: "Downtown Seattle",
        area: "downtown-seattle",
        summary:
          "A polished downtown Seattle option for central stays, events, and airport pickups that end near the financial district.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.00",
        durationMinutes: 28,
        priority: 31,
      },
      {
        slug: "alexis-royal-sonesta-hotel-seattle",
        name: "The Alexis Royal Sonesta Hotel Seattle",
        address: "1007 1st Ave, Seattle, WA 98104, USA",
        neighborhood: "Downtown Seattle",
        area: "downtown-seattle",
        summary:
          "A downtown hotel that works well for waterfront access, business stays, and premium airport arrivals into central Seattle.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.10",
        durationMinutes: 28,
        priority: 32,
      },
      {
        slug: "edgewater-hotel",
        name: "The Edgewater Hotel",
        address: "2411 Alaskan Way, Seattle, WA 98121, USA",
        neighborhood: "Seattle waterfront",
        area: "waterfront",
        summary:
          "A waterfront stay that works especially well for cruise extensions, waterfront plans, and travelers who want to stay near Pier 66.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "16.80",
        durationMinutes: 32,
        priority: 12,
      },
      {
        slug: "four-seasons-hotel-seattle",
        name: "Four Seasons Hotel Seattle",
        address: "99 Union St, Seattle, WA 98101, USA",
        neighborhood: "Seattle waterfront",
        area: "waterfront",
        summary:
          "A waterfront luxury stay for travelers combining Sea-Tac arrivals with downtown plans, premium stays, or cruise-adjacent nights.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.60",
        durationMinutes: 29,
        priority: 13,
      },
      {
        slug: "inn-at-the-market",
        name: "Inn at the Market",
        address: "86 Pine St, Seattle, WA 98101, USA",
        neighborhood: "Seattle waterfront",
        area: "waterfront",
        summary:
          "A Pike Place and waterfront stay that works well for cruise pre-stays, central Seattle nights, and airport arrivals heading straight into the market area.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.90",
        durationMinutes: 30,
        priority: 14,
      },
      {
        slug: "seattle-marriott-waterfront",
        name: "Seattle Marriott Waterfront",
        address: "2100 Alaskan Way, Seattle, WA 98121, USA",
        neighborhood: "Seattle waterfront",
        area: "waterfront",
        summary:
          "A strong waterfront hotel choice for cruise pre-stays, downtown visits, and travelers who want a direct airport ride near the piers.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "16.30",
        durationMinutes: 31,
        priority: 15,
      },
      {
        slug: "thompson-seattle",
        name: "Thompson Seattle",
        address: "110 Stewart St, Seattle, WA 98101, USA",
        neighborhood: "Seattle waterfront",
        area: "waterfront",
        summary:
          "A downtown waterfront stay near Pike Place that works well for premium city arrivals and cruise-adjacent nights.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.70",
        durationMinutes: 30,
        priority: 33,
      },
      {
        slug: "state-hotel-seattle",
        name: "The State Hotel",
        address: "1501 2nd Ave, Seattle, WA 98101, USA",
        neighborhood: "Seattle waterfront",
        area: "waterfront",
        summary:
          "A compact downtown stay close to Pike Place and the waterfront for shorter Seattle visits and cruise pre-stays.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.50",
        durationMinutes: 29,
        priority: 34,
      },
      {
        slug: "kimpton-palladian-hotel",
        name: "Kimpton Palladian Hotel",
        address: "2000 2nd Ave, Seattle, WA 98121, USA",
        neighborhood: "Seattle waterfront",
        area: "waterfront",
        summary:
          "A Belltown and waterfront hotel option that keeps Pike Place, Pier 66, and downtown Seattle close together.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.90",
        durationMinutes: 30,
        priority: 35,
      },
      {
        slug: "charter-hotel-seattle",
        name: "The Charter Hotel Seattle, Curio Collection by Hilton",
        address: "1610 2nd Ave, Seattle, WA 98101, USA",
        neighborhood: "Seattle waterfront",
        area: "waterfront",
        summary:
          "A central waterfront stay for travelers who want an easy route between Sea-Tac, Pike Place, and the cruise corridor.",
        airportRouteSlug: "seatac-downtown-core",
        distanceMiles: "15.60",
        durationMinutes: 29,
        priority: 36,
      },
      {
        slug: "hyatt-regency-bellevue",
        name: "Hyatt Regency Bellevue",
        address: "900 Bellevue Way NE, Bellevue, WA 98004, USA",
        neighborhood: "Downtown Bellevue",
        area: "bellevue",
        summary:
          "A central Bellevue hotel for business arrivals, Eastside meetings, and airport transfers that end near the Bellevue core.",
        airportRouteSlug: "seatac-bellevue-core",
        distanceMiles: "18.40",
        durationMinutes: 33,
        priority: 16,
      },
      {
        slug: "westin-bellevue",
        name: "The Westin Bellevue",
        address: "600 Bellevue Way NE, Bellevue, WA 98004, USA",
        neighborhood: "Downtown Bellevue",
        area: "bellevue",
        summary:
          "A good Bellevue base for Eastside work trips, upscale stays, and direct Sea-Tac arrivals without a downtown detour.",
        airportRouteSlug: "seatac-bellevue-core",
        distanceMiles: "18.10",
        durationMinutes: 32,
        priority: 17,
      },
      {
        slug: "w-bellevue",
        name: "W Bellevue",
        address: "10455 NE 5th Pl, Bellevue, WA 98004, USA",
        neighborhood: "Downtown Bellevue",
        area: "bellevue",
        summary:
          "A modern Bellevue stay for Eastside business arrivals, events, and travelers who want a premium hotel in the Bellevue core.",
        airportRouteSlug: "seatac-bellevue-core",
        distanceMiles: "18.30",
        durationMinutes: 33,
        priority: 18,
      },
      {
        slug: "ac-hotel-bellevue",
        name: "AC Hotel by Marriott Seattle Bellevue/Downtown",
        address: "208 106th Pl NE, Bellevue, WA 98004, USA",
        neighborhood: "Downtown Bellevue",
        area: "bellevue",
        summary:
          "A practical Bellevue option for Eastside stays, office visits, and airport transfers that end close to the downtown Bellevue core.",
        airportRouteSlug: "seatac-bellevue-core",
        distanceMiles: "18.60",
        durationMinutes: 34,
        priority: 19,
      },
      {
        slug: "bellevue-club-hotel",
        name: "Bellevue Club Hotel",
        address: "11200 SE 6th St, Bellevue, WA 98004, USA",
        neighborhood: "Downtown Bellevue",
        area: "bellevue",
        summary:
          "A refined Bellevue stay for longer Eastside visits, executive trips, and direct airport arrivals near the Bellevue core.",
        airportRouteSlug: "seatac-bellevue-core",
        distanceMiles: "17.90",
        durationMinutes: 32,
        priority: 37,
      },
      {
        slug: "hilton-bellevue",
        name: "Hilton Bellevue",
        address: "300 112th Ave SE, Bellevue, WA 98004, USA",
        neighborhood: "Downtown Bellevue",
        area: "bellevue",
        summary:
          "A strong Bellevue business hotel for Eastside office trips, conferences, and direct Sea-Tac transfers.",
        airportRouteSlug: "seatac-bellevue-core",
        distanceMiles: "17.60",
        durationMinutes: 31,
        priority: 38,
      },
      {
        slug: "seattle-marriott-bellevue",
        name: "Seattle Marriott Bellevue",
        address: "200 110th Ave NE, Bellevue, WA 98004, USA",
        neighborhood: "Downtown Bellevue",
        area: "bellevue",
        summary:
          "A downtown Bellevue stay close to offices, shopping, and direct airport rides into the Eastside core.",
        airportRouteSlug: "seatac-bellevue-core",
        distanceMiles: "18.20",
        durationMinutes: 33,
        priority: 39,
      },
      {
        slug: "residence-inn-bellevue-downtown",
        name: "Residence Inn by Marriott Bellevue Downtown",
        address: "605 114th Ave SE, Bellevue, WA 98004, USA",
        neighborhood: "Downtown Bellevue",
        area: "bellevue",
        summary:
          "A useful Bellevue option for longer stays, family luggage, and travelers planning more than one airport run.",
        airportRouteSlug: "seatac-bellevue-core",
        distanceMiles: "18.00",
        durationMinutes: 32,
        priority: 40,
      },
      {
        slug: "embassy-suites-bellevue",
        name: "Embassy Suites by Hilton Seattle Bellevue",
        address: "3225 158th Ave SE, Bellevue, WA 98008, USA",
        neighborhood: "Bellevue",
        area: "bellevue",
        summary:
          "A Bellevue stay that works well for family trips, office visits, and travelers who want extra space after landing at Sea-Tac.",
        airportRouteSlug: "seatac-bellevue-core",
        distanceMiles: "19.80",
        durationMinutes: 35,
        priority: 41,
      },
      {
        slug: "hotel-116-bellevue",
        name: "Hotel 116, A Coast Hotel Bellevue",
        address: "625 116th Ave NE, Bellevue, WA 98004, USA",
        neighborhood: "Bellevue",
        area: "bellevue",
        summary:
          "A convenient Bellevue hotel for Eastside stays, quieter nights outside downtown Seattle, and direct airport pickups.",
        airportRouteSlug: "seatac-bellevue-core",
        distanceMiles: "18.50",
        durationMinutes: 33,
        priority: 42,
      },
      {
        slug: "woodmark-hotel-kirkland",
        name: "Woodmark Hotel & Still Spa",
        address: "1200 Carillon Point, Kirkland, WA 98033, USA",
        neighborhood: "Kirkland waterfront",
        area: "kirkland",
        summary:
          "A waterfront Kirkland stay for travelers headed north of Bellevue who still want a direct airport ride.",
        airportRouteSlug: "seatac-kirkland-core",
        distanceMiles: "22.50",
        durationMinutes: 39,
        priority: 20,
      },
    ],
    settings: {
      companyName: "seatac.co",
      dispatchPhone: "(206) 737-0808",
      dispatchEmail: "hello@seatac.co",
      dispatchRules: {
        pickupBufferMinutes: 60,
        dropoffBufferMinutes: 60,
        minimumTransferMinutes: 15,
        fallbackTransferMinutes: 30,
        defaultRouteDurationMinutes: 90,
      },
      bookingConstraints: {
        customTripDefaultPricing: "distance",
        enableDistancePricing: true,
        enableFlatPricing: true,
        enableHourlyPricing: true,
        chargeBagsOnDistance: false,
        chargeBagsOnEvent: false,
        chargeBagsOnFlat: false,
        chargeBagsOnHourly: false,
        chargeMileageOnDistance: true,
        chargeMileageOnEvent: false,
        chargeMileageOnFlat: false,
        chargeMileageOnHourly: false,
        chargePassengersOnDistance: false,
        chargePassengersOnEvent: false,
        chargePassengersOnFlat: false,
        chargePassengersOnHourly: false,
        perMileFee: 0,
        perBagFee: 0,
        perPassengerFee: 0,
        hourlyMinimumHours: 3,
        hourlyServiceFee: 0,
        minimumLeadMinutes: 120,
        operatingHoursStart: "04:00",
        operatingHoursEnd: "23:00",
        maxAdvanceDays: 180,
        presetRouteDefaultPricing: "flat",
        timeZone: "America/Los_Angeles",
      },
      coverage: [
        "Sea-Tac Airport",
        "Sea-Tac hotels",
        "Downtown Seattle",
        "Bellevue",
        "Kirkland",
        "Mercer Island",
        "South Lake Union",
      ],
    },
  },
} as const;
