export const seededSites = [
  {
    slug: "pierlimo",
    name: "Pierlimo",
    domain: "pierlimo.com",
    themeKey: "pierlimo",
  },
  {
    slug: "seatacdrive",
    name: "seatac.co",
    domain: "seatac.co",
    themeKey: "seatacdrive",
  },
] as const;

export const seededSiteData = {
  pierlimo: {
    chauffeurs: [
      {
        name: "Ameer Nuri",
        phone: "(206) 555-0112",
        color: "emerald",
        displayOrder: 1,
      },
      {
        name: "Maya Chen",
        phone: "(206) 555-0118",
        color: "sky",
        displayOrder: 2,
      },
      {
        name: "Jordan Alvarez",
        phone: "(206) 555-0147",
        color: "amber",
        displayOrder: 3,
      },
    ],
    vehicles: [
      {
        slug: "executive-sedan",
        name: "Executive Sedan",
        summary:
          "Discrete black-car service for Sea-Tac transfers, boardroom arrivals, and downtown hotel pickups.",
        passengersMin: 1,
        passengersMax: 3,
        bagsMin: 0,
        bagsMax: 3,
        quantity: 3,
        basePrice: "95.00",
        perMileRate: "3.25",
        hourlyRate: "95.00",
        image:
          "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
        displayOrder: 1,
      },
      {
        slug: "luxury-suv",
        name: "Luxury SUV",
        summary:
          "Executive comfort with extra luggage room for Bellevue runs, investor dinners, and family airport departures.",
        passengersMin: 1,
        passengersMax: 6,
        bagsMin: 0,
        bagsMax: 6,
        quantity: 2,
        basePrice: "135.00",
        perMileRate: "4.15",
        hourlyRate: "125.00",
        image:
          "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80",
        displayOrder: 2,
      },
      {
        slug: "sprinter-van",
        name: "Sprinter Van",
        summary:
          "Group movement for wedding parties, conference teams, and multi-stop private transportation.",
        passengersMin: 4,
        passengersMax: 12,
        bagsMin: 2,
        bagsMax: 12,
        quantity: 1,
        basePrice: "245.00",
        perMileRate: "6.50",
        hourlyRate: "185.00",
        image:
          "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
        displayOrder: 3,
        siteAssignments: ["pierlimo", "seatacdrive"],
      },
    ],
    routes: [
      {
        slug: "seatac-downtown-seattle",
        name: "Sea-Tac Airport to Downtown Seattle",
        mode: "airport",
        origin: "Sea-Tac Airport",
        destination: "Downtown Seattle",
        basePrice: "118.00",
        mileage: "15.00",
        durationMinutes: 28,
      },
      {
        slug: "seatac-bellevue",
        name: "Sea-Tac Airport to Bellevue",
        mode: "airport",
        origin: "Sea-Tac Airport",
        destination: "Bellevue",
        basePrice: "132.00",
        mileage: "18.00",
        durationMinutes: 32,
      },
      {
        slug: "seatac-redmond",
        name: "Sea-Tac Airport to Redmond",
        mode: "airport",
        origin: "Sea-Tac Airport",
        destination: "Redmond",
        basePrice: "146.00",
        mileage: "24.00",
        durationMinutes: 40,
      },
      {
        slug: "downtown-bellevue-corporate",
        name: "Downtown Seattle to Bellevue Corporate Corridor",
        mode: "corporate",
        origin: "Downtown Seattle",
        destination: "Bellevue",
        basePrice: "124.00",
        mileage: "12.00",
        durationMinutes: 26,
      },
      {
        slug: "bellevue-redmond-corporate",
        name: "Bellevue to Redmond Tech Campus",
        mode: "corporate",
        origin: "Bellevue",
        destination: "Redmond",
        basePrice: "112.00",
        mileage: "10.00",
        durationMinutes: 24,
      },
      {
        slug: "hourly-seattle-minimum",
        name: "Seattle Hourly Charter",
        mode: "hourly",
        origin: "Flexible pickup",
        destination: "As directed",
        basePrice: "0.00",
        mileage: "0.00",
        durationMinutes: 0,
      },
    ],
    settings: {
      companyName: "Pierlimo",
      dispatchPhone: "(206) 555-0142",
      dispatchEmail: "reservations@pierlimo.com",
      dispatchRules: {
        pickupBufferMinutes: 60,
        dropoffBufferMinutes: 60,
        minimumTransferMinutes: 15,
        fallbackTransferMinutes: 30,
        defaultRouteDurationMinutes: 90,
      },
      bookingConstraints: {
        minimumLeadMinutes: 120,
        operatingHoursStart: "04:00",
        operatingHoursEnd: "23:00",
        maxAdvanceDays: 180,
        timeZone: "America/Los_Angeles",
      },
      coverage: [
        "Sea-Tac Airport",
        "Downtown Seattle",
        "Bellevue",
        "Redmond",
        "Kirkland",
        "Mercer Island",
        "South Lake Union",
        "Capitol Hill",
        "Waterfront hotels",
      ],
    },
  },
  seatacdrive: {
    chauffeurs: [
      {
        name: "Devin Brooks",
        phone: "(206) 555-0191",
        color: "violet",
        displayOrder: 1,
      },
      {
        name: "Sofia Patel",
        phone: "(206) 555-0184",
        color: "rose",
        displayOrder: 2,
      },
      {
        name: "Elias Grant",
        phone: "(206) 555-0166",
        color: "slate",
        displayOrder: 3,
      },
    ],
    vehicles: [
      {
        slug: "airport-sedan",
        name: "Airport Sedan",
        summary:
          "Focused Sea-Tac black-car service for direct terminal pickups, departures, and clean downtown drop-offs.",
        passengersMin: 1,
        passengersMax: 3,
        bagsMin: 0,
        bagsMax: 3,
        quantity: 3,
        basePrice: "89.00",
        perMileRate: "3.10",
        hourlyRate: "90.00",
        image:
          "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
        displayOrder: 1,
      },
      {
        slug: "airport-suv",
        name: "Airport SUV",
        summary:
          "Extra luggage room for families, tech travelers, and Bellevue airport transfers.",
        passengersMin: 1,
        passengersMax: 6,
        bagsMin: 0,
        bagsMax: 6,
        quantity: 2,
        basePrice: "129.00",
        perMileRate: "4.05",
        hourlyRate: "122.00",
        image:
          "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80",
        displayOrder: 2,
      },
    ],
    routes: [
      {
        slug: "seatac-downtown-core",
        name: "Sea-Tac to Downtown Seattle",
        mode: "airport",
        origin: "Sea-Tac Airport",
        destination: "Downtown Seattle",
        basePrice: "109.00",
        mileage: "15.00",
        durationMinutes: 27,
      },
      {
        slug: "seatac-bellevue-core",
        name: "Sea-Tac to Bellevue",
        mode: "airport",
        origin: "Sea-Tac Airport",
        destination: "Bellevue",
        basePrice: "124.00",
        mileage: "18.00",
        durationMinutes: 31,
      },
      {
        slug: "seatac-kirkland-core",
        name: "Sea-Tac to Kirkland",
        mode: "airport",
        origin: "Sea-Tac Airport",
        destination: "Kirkland",
        basePrice: "138.00",
        mileage: "23.00",
        durationMinutes: 38,
      },
      {
        slug: "downtown-bellevue-business",
        name: "Downtown Seattle to Bellevue Business Corridor",
        mode: "corporate",
        origin: "Downtown Seattle",
        destination: "Bellevue",
        basePrice: "118.00",
        mileage: "12.00",
        durationMinutes: 25,
      },
      {
        slug: "seatac-hourly-charter",
        name: "SeaTacDrive Hourly Charter",
        mode: "hourly",
        origin: "Flexible pickup",
        destination: "As directed",
        basePrice: "0.00",
        mileage: "0.00",
        durationMinutes: 0,
      },
    ],
    settings: {
      companyName: "seatac.co",
      dispatchPhone: "(206) 555-0188",
      dispatchEmail: "hello@seatac.co",
      dispatchRules: {
        pickupBufferMinutes: 60,
        dropoffBufferMinutes: 60,
        minimumTransferMinutes: 15,
        fallbackTransferMinutes: 30,
        defaultRouteDurationMinutes: 90,
      },
      bookingConstraints: {
        minimumLeadMinutes: 120,
        operatingHoursStart: "04:00",
        operatingHoursEnd: "23:00",
        maxAdvanceDays: 180,
        timeZone: "America/Los_Angeles",
      },
      coverage: [
        "Sea-Tac Airport",
        "Sea-Tac hotels",
        "Downtown Seattle",
        "Bellevue",
        "Kirkland",
        "Mercer Island",
        "South Lake Union",
      ],
    },
  },
} as const;
