services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: pierlimo_next
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
